#! /usr/bin/python3
from os import system as S
S("clear")

# ----- Ввод основных данных
N, world, ma, mi= int(input("Введите количество чисел: ")), 0, 0, 1000000000

# ----- Мы вводим и сразу определяем, какое это число, самое главное, чтобы
#       это число не было кратно 15 и произведение двух максимальных чисел не
#       было кратно 15

for i in range(N): 
    world = int(input("Введите число: "))
    
    if world > ma and world % 15 != 0 and mi != 0 and ma != 0:
        if world * ma % 15 != 0:
            mi, ma = ma, world
    elif (mi == 0 or ma == 0) and (world % 15 != 0):
        mi, ma = ma, world

# ----- Ответ
print(ma*mi)
