#! /usr/bin/python3
# This program created for setup terminal window size
from os import system as S
S("clear")
for k in range(320 , 49, -1):
    for i in range(0, k+1):
        print("#", end='')
    print("\n", k, "\n")

input("Press ENTER to continue...")
S("clear")

for k in range(1, 51):
    print(k)

print("That\'s it")
input("Press ENTER to continue...")


