<Button>:
	size_hint: 0.5, 0.5
	background_color: 1, .35, 1, .4
<FloatLayout>:
	Button:
		id: btn
		text: "PRESS ME!!!" if btn.state == "normal" else ("YES!"*13+"\n")*18
		color: 1, 0, 0, 1
		background_color: 1, .5, 0, 1
		pos_hint: {"x": .25, "y": .25}

	Button:
		id: snd_btn
		size_hint: .25, .25
		pos_hint: {"x": .1, "y": .3}
		text: "PRESS THAT, PLEASE!!" if snd_btn.state == "normal" else ("A"*666+"\n")*66
