#! /usr/bin/python3
from os import system as S
from random import randint as R


X = open("inX.txt", 'w')
Y = open("inY.txt", 'w')

for i in range(30):
    X.write(str(R(-512, 512)) + ' ')
    Y.write(str(R(-511, 512)) + ' ')

X.close()
Y.close()

