#! /bin/sh

fpc main.pas && ./main; less out.txt; rm main main.o
echo 
read -p "Delete all txt files? [no/yes]=[0/1] " choice

if [ $choice -eq 1 ]; then
    rm inX.txt inY.txt out.txt
    echo "Done"
fi
