#! /bin/sh

fpc main.pas && ./create_test && ./main; less out.txt; rm main main.o
echo 
read -p "Delete all txt files? [0/1] " choice

if [ $choice -eq 0 ]; then
    rm inX.txt inY.txt out.txt
    echo "Done"
fi
