#! /usr/bin/python3

# Here some functions
from math import sqrt as sqr
# Remember, 
def one(a, b=2, c=50):
    D = b**2 - 4*a*c
    if D < 0:
        print("DISCRIMINANT LOWER THEN 0!")
        return 0
    else:
        D = sqr(D)
        x1 = (-b-D)/2
        x2 = (-b+D)/2
        print("X1 = {}, X2 = {}".format(x1, x2))

one(int(input("Input a: ")), int(input("Input b: ")), int(input("Input c: ")))

x = input("This text will storage in global variable 'x'")
def use_x():
    print("\nx was declare out of function. In that case we are use 'global'")
    global x
    print("Trust me, x is {}".format(x))

use_x()
use_x()
x = input("This text will storage in global variable 'x'")
use_x()
print("\nNow, I will show you try-except-finaly construction:\n")

try:
    print(x//0)
except:
    print("I am trying divide string by zero. Hm, maybe I made a mistake...")
finally:
    print("So, in try-block we put code, which could make a mistake. If it happens, calls except-block. Finally-block always execute")
o = input("Input ENTER")
del o


import os
os.system("clear")
print("Let's try another try-except-finally construction:\n\n")

try:
    result = 0//0
    s = "Stroka"/3
except ZeroDivisionError:
    print("Now, we just divide by zero and try divide stroke by 3. In except condition I put 'ZeroDivisionError.'")
finally:
    print("There is maany errors, so you can read about it in python's documentation")

o = input("Input ENTER")
del o
os.system("clear")


