#! /usr/bin/python3
# Updated 17.05.20
from os import system as S
S('clear')

def number_input(num):
    if num[0] == '-':
        if num[1:].isdigit():
            return int(num)
    elif num.isdigit():
            return int(num)
    else:
        return 1
# ---------------------------[Главный исполнительный блок]-------------------- #
    c = input("Введите 'q', завершить программу, а чтобы продолжить, нажмите ENTER: ")
    if c == 'q':
        break
    S('clear')

    a = input("Введите a: ")
    if a == '0':
        print("это уже не квадратное уравнение, лмао\n\n")
        continue
    a = number_input(a)

    b, c = number_input(input("Введите b: ")), number_input(input("Введите c: "))

    D = b**2 + 4*a*c*(-1)
    if D < 0:
        print("Дискриминант отрицателен (", D, ")", sep='')
        continue
    elif D == 0:
        print("Корень этого уравнения:", (-b)/(2*a))
    else:
        x1, x2 = ((-b) - D**(1/2))/(2*a), ((-b) + D**(1/2))/(2*a)
        print(f"Корни этого уравнения: {x1} и {x2}\nДискриминант: {D}")

    input("Чтобы продолжить, нажмиите ENTER...")
    S('clear')
