#! /usr/bin/python3
from os import system as S
S("clear")
print("\nМы закончили на странице 97. Прошу запомнить следующее:\n\
    r - чтение\n\
    w - аналог '>'\n\
    a - аналог '>>'\n\
    b - двоичный режим, бинарные файлы\n")

story = open("story.txt", "r")
print(story.read(128))
c = input("Сие команда читает [байт] за байтом. ENTER")
S("clear")
print("\n", story.read())
story.close()

c = input("\n _____\n[ENTER]\n")
S("clear")

again = open("future.txt", "r+")
for lines in again:
    print(lines, "|")
again.close()
again = open("future.txt", "r")
print("Количество строк в будущем равно", len(again.readlines()))
again.close()
c = input("Теперь запишем несколько строк в будущее, но сначала ENTER...")

S("clear")

new = open("past.txt", "a")
print(new.write(input("Введите сообщение, которое хотите передать потомкам, затем нажмите ENTER...  ")), "байт записано")
new.close()
c = input("\nENTER...\n")
S("clear")

new = open("past.txt", "r")
print("Мы получили послание. Вот оно:\n", new.read())
new.close()

new = open("past.txt", "w")
print("Удаляем сообщение")
new.close()

with open("past.txt", "w") as f:
    print(f.write("ЛЕЛЬЕЛЬЕЛЬЕЛЬЕЛЬЕЛЬЕЛЬЕЬЛЬЛЕЬЛЕЬЛЕЬЛЕ"), "кол-во байт записано")

print("На сим, пятый день окончен")
