#! /usr/bin/python3
from os import system as sys
sys("clear")
print("Страница 72. Тут рассказывают о строках.")

print("""
Одна строка
две строки
три     строки""")

ara = "ARA ARA"
print(ara[:4], ara[4:])
ara = "Мы не изменяемы"
try:
    ara[3] = '0'
except:
    ara = "Мы ДЕЙСТВИТЕЛЬНО неизменяемы. Как кортежи"
finally:
    print(ara)


c = input("А сейчас будем использовать методы. Нажми клавишу ENTER, чтобы продолжить.")
sys("clear")
apa = input("\nВведите пару предложений, потом нажмите ENTER:\n")
print(apa.upper(), "КАПС ЖИВ")
print(apa.lower(), "капс мёртв")
ara = ara.lower()
print(ara.capitalize())

ara = ara.split(".")
print("А тут мы из строки сделали массив: {}. Вспоминаем про эту строку '{}'. Добавляем туда символ:".format(ara, apa))

apa = "#".join(apa)
print(apa, "\nДалее, разделяем по этому символу:")
apa = apa.split("#")
print(apa)
apoa = "омбо ".join("КККd f") # Обрати внимание на то, что вконце стоит пробел.
print(apoa)
c = input("Погнали дальше(нажми ENTER)")
sys("clear")

apa = "".join(apa)
print("Как вы могли заметить, метод join может из списка делать строку:", apa + "\n")

print("Метод strip удаляет пробельные символы.", apa.strip())
ara = "".join(ara)
ara = ara + "Мы"
print(ara.replace("Мы", "Ты"))
    # А тут вы видите пример работы метода .index(). Не забудь, что он выводит индекс при первом вхождении
for k in ara:
    print(ara.index(k))
print(ara[3:7])

# startswith и endswith определяют, есть ли подстрока в строке с начала или с конца соответственно
print(ara.startswith("ararararara"))
