#! /usr/bin/python3
from os import system as S

print("\n==[Первая программа]==")
print("Вчера мы написали " + input() + ". Вчера мы ходили в " + input() + ".")
c = input("\n\n...")
S("clear")

print("\n==[Вторая программа]==")
s = "Где это? Кто это? Когда это?".split("? ")
s[0], s[1] = s[0] + '?', s[1] + '?'
print(s)
