#! /usr/bin/python3
from os import system as S
S("clear")

# ---------------------------[Запуск программы]--------------------------------
# Титульный экран
print("\n\tBASE-01 v0.1 29.03.2020\n\n\tMADE BY SPACE UNICORN!")
S("sleep 2s")
S("clear")

# Генерация списка пограмм
PROGRAMS = []
S("ls manuals/ > list")
F = open('list', 'r')
l = ''
while True:
    l = F.readline()
    if l == '': break
    else: PROGRAMS.append(l[:-5])
F.close()
S("rm list")

# ---------------------------[Блок функций]------------------------------------

# Функция выбора программы
def choose_program():
    for i in PROGRAMS:
        print("  *", i)
    print("Введите 'q', если хотите вернуться в предыдущее меню")
    choose = []
    choose.append('')
    while True:
        choose[0] = input(": ")
        if choose[0].lower() == 'q':
            return [0, 0]
        if choose[0] not in PROGRAMS:
            print("Вы неверно ввели данные")
        else: break
    choose.append('')
    road = 'manuals/' + choose[0] + '.txt'
    F = open(road, 'r')
    choose[1] = F.readline()
    F.close()
    return choose

# Вызов справки
def manual():
    global PROGRAMS
    print("О какой программе хотите узнать?")
    choose = choose_program()
    if choose[0] == 0:
        return
    choose[0] = 'manuals/' + choose[0] + ".txt" \
            if (".txt" not in choose[0]) else choose[0]
    with open(choose[0], 'r') as F:
        F.readline()
        print(F.read())
    input("...")
    S("clear")

# Запуск программы
def program():
    global PROGRAMS
    print("Какую программу хотите запустить?")
    choose = choose_program()
    if choose[0] == 0:
        return
    command = "cd {} ; ./{}".format(choose[1][:-1], choose[0])
    S(command)
    input("...")

# ---------------------------[Главный исполнительный блок]---------------------
while True:
    print("Ввести MAN     -- вызов справки\nНажать 'ENTER' -- вызов \
программы\nВвести q       -- выход из BASE-01")
    c = input(": ")
    if c.upper() == 'MAN': manual()
    elif c == '': program()
    elif c.lower() == 'q': break
    S("clear")
