#! /usr/bin/python3
from os import system as S
S("clear")

# ---------------------------[Запуск программы]--------------------------------
# Титульный экран
print("\n\tBASE-01 v0.1 25.03.2020\n\n\tMADE BY SPACE UNICORN!")
S("sleep 2s")
S("clear")

# Генерация списка пограмм
PROGRAMS = []
S("ls manuals/ > list")
F = open('list', 'r')
l = ''
while True:
    l = F.readline()
    if l == '': break
    else: PROGRAMS.append(l[:-5])
F.close()
S("rm list")
# ---------------------------[Блок функций]------------------------------------

# Функция выбора программы
def choose_program():
    for i in PROGRAMS:
        print(i)
    choose = []
    choose.append('')
    while True:
        choose[0] = input(": ")
        if choose[0] not in PROGRAMS:
            print("Вы неверно ввели данные")
        else: break
    choose.append('')
    road = 'manuals/' + choose[0] + '.txt'
    print(road)
    F = open(road, 'r')
    choose[1] = F.readline()
    F.close()
    return choose

# Вызов справки
def manual():
    global PROGRAMS
    print("О какой программе хотите узнать?")
    choose = choose_program()
    choose[0] = 'manuals/' + choose[0] + ".txt" \
            if (".txt" not in choose[0]) else choose[0]
    with open(choose[0], 'r') as F:
        F.readline()
        print(F.read())
    input("...")
    S("clear")

# Запуск программы
def program():
    global PROGRAMS
    print("Какую программу хотите запустить?")
    choose = choose_program()
    S(choose[1])
    input("...")
    

# ---------------------------[Главный исполнительный блок]---------------------
while True:
    print("0 -- вызов справки\n1 -- вызов программы\n2 -- выход из BASE-01")
    c = input(": ")
    if c == '0': manual()
    elif c == '1': program()
    elif c == '2': break
    else: print("'{}' нет такой опции".format(c))
    S("clear")
