#! /usr/bin/python3
from os import system as S
from os.path import abspath
S("clear")
PATH = abspath("") + '/'

# ---------------------------[Запуск программы]--------------------------------
# Титульный экран
print("\n\tBASE-01 v0.1.4\n\n\tMADE BY SPACE UNICORN!\n\n\n\
Создан 29.03.2020\nПоследнее обновление 06.06.2020")

S("sleep 2s")
S("clear")

# Генерация списка пограмм
PROGRAMS, command = [], "ls {}help/ > list".format(PATH)
S(command)
F = open('list', 'r')
l = ''
while True:
    l = F.readline()
    if l == '': break
    else: PROGRAMS.append(l[:-5])
F.close()
S("rm list")

# ---------------------------[Блок функций]------------------------------------

# Функция выбора программы
def choose_program():
    for i in PROGRAMS:
        print("  *", i)
    print("Введите 'q', если хотите вернуться в предыдущее меню")
    choose = []
    choose.append('')
    while True:
        choose[0] = input(": ")
        if choose[0].lower() == 'q':
            return [0, 0]
        if choose[0] not in PROGRAMS:
            print("Вы неверно ввели данные")
        else: break
    choose.append('')
    road = PATH + 'help/' + choose[0] + '.txt'
    F = open(road, 'r')
    choose[1] = F.readline()
    F.close()
    return choose

# Вызов справки
def manual():
    global PROGRAMS
    print("О какой программе хотите узнать?")
    choose = choose_program()
    if choose[0] == 0:
        return
    choose[0] = PATH + 'help/' + choose[0] + ".txt" \
            if (".txt" not in choose[0]) else choose[0]
    with open(choose[0], 'r') as F:
        F.readline()
        print(F.read())
    input(". . . E N T E R . . .")
    S("clear")

# Запуск программы
def program():
    global PROGRAMS
    print("Какую программу хотите запустить?")
    choose = choose_program()
    if choose[0] == 0:
        return
    command = "cd {0}{1}; ./{2}".format(PATH, choose[1][:-1], choose[0])
    S(command)
    input(". . . E N T E R . . .")

# дополнительное меню
def super_menu():
    print('--------------------------------')
    print("""
    ipython3  -- запуск интерактивной оболочки
    python3   -- запуск обычной оболочки python
    edit      -- редактировать существующую программу
    q         -- вернуться обратно
    """)
    c = input(": ")
    if c == 'ipython3': S("ipython3")
    elif c == 'python3': S("python3")
    elif c == 'edit':
        choose = choose_program()
        if choose[0] == 0:
            return
        command = "cd {}{} ; vim {}".format(PATH, choose[1][:-1], choose[0])
        S(command)
    elif c == 'q': return 0


# ---------------------------[Главный исполнительный блок]---------------------
while True:
    print("MAN -- справки\nНажать 'ENTER' -- вызов программы\
\no -- вызов дополнительных опций\n\
q -- выход из BASE-01")
    c = input(": ")
    if c.upper() == 'MAN': manual()
    elif c == '': program()
    elif c.lower() == 'o': super_menu()
    elif c.lower() == 'q': break
    S("clear")
