#! /usr/bin/python3

# SQUARE TABLE. All rights are left. Made by SPACE UNICORNS!!!
from os import system as S
s = "clear"
S(s)

# ---------------------------[Главный исполнемый блок]-------------------------

# Цвета
G , B, C, reset= '\033[42m', '\033[44m', '\033[46m', '\033[0m'

# Вывод шапки таблицы
numbers = [str(x+1) for x in range(0, 9)]
numbers =  " "*5 + "    ".join(numbers)
print(G + numbers, reset)

# Вывод содержимое таблицы
for i in range(1, 10):
    print(B + "{:<2,d}".format(i) + reset, end='')
    for j in range(1, 10):
        print(C + "{:>4d}".format((j+i*10)**2), reset, end='')
    print()

input("Чтобы завершить программу, нажмите Enter...")
