#! /usr/bin/python3
from os import system as S
s = 'clear'
S(s)

print("\nПервая задача\n\n")
from random import randint as rnd

spisok = list()
for i in range(10):
    spisok.append(rnd(-99, 100))
print(spisok)

second = [x**2 for x in spisok]
print(second)

negative = [x for x in spisok if x < 0]
print(negative)

positive = [x for x in spisok if x > 0]

input("\n\n\nНажмите ENTER, чтобы продолжить...")
S(s)


print("\nВторая задача\n\n")

AO = ["SAS"]*3 + ["SOS"]*5

if input("input SAnS: ") in AO:
    print("WeeW")
else:
    print("EaaE")
