#! /usr/bin/python3

print("I am finished on page 58")

print("So, hello, Today we will learn about containers.")

from os import system as sys

print("\n\nLet's create a simple list")
simple_note = list()
simple_note.append(input("PRINT SOMETHING: "))
simple_note.append("ANOTHER STRING")
simple_note.append(bool("Hello"))
simple_note.append(simple_note)
simple_note.append("DELETE MEEE!")

print("\nSo, here a list, that I create: {0}. Inside [..] we see: {2}. Let's make a request for this element: {1}".format(simple_note, simple_note[-1], simple_note[3]))
simple_note.pop()
print("\nAnd then, check: {}".format(simple_note))
c = input("PRESS ENTER TO CONTINUE")
sys("clear")

#-----------------------------------------
print("\n",simple_note[3])
print(simple_note[3][3])
print(simple_note[3][3][3])
print(simple_note[3][3][3][3])
print(simple_note[3][3][3][3][3])
print(simple_note[3][3][3][3][3][3], "\nI don't now, how does it work... I made infinite list... So, let's set simple_note[3][3][3]... as 10")
simple_note[3][3][3][3][3] = 10
print(simple_note, "\n", simple_note[3])
c = input("That's it! Press ENTER to continue...")
sys("clear")
#----------------------------------------

print("\nINtel INside NOT")

print("Does third element in simple_note is simple_note? --", simple_note[3] in simple_note)
simple_note.pop(len(simple_note)//2)
print("~    ~   ~\n~    ~   ~\nLen and pop =", simple_note)
print("REMEMBER, TUPLE OBJECT DOES NOT SUPPORT ITEM ASSIGNMENT")
c = input("Press ENTER to play with dictionary...")
sys("clear")

#----------------------------------------

persona = {"Name":input("\nInput a name: "), "age":input("Input age: "), "gender":input("Input gender: ")}
print("So, your name is '{}'.I think we should delete information about your gender, because that does not mean for uS.".format(persona["Name"]))
del persona["gender"]
print(persona)
inv = [["sword", 1], ["bread", 5]]

print(persona)
for key, value in persona.items():
    print(key, "is key for value", value)

c = input("Press ENTER to say 'Goodbye'")
