#! /usr/bin/python3
# ---------------------------[титульный экран]---------------------------------
from os import system as S
s = 'clear'
S(s)
print("""
        Dramatic v0.02. All rights are left.
        Made by SPACE UNICORNS!!!
      """)
S('sleep 2s')
S(s)

# ---------------------------[Блок функций]------------------------------------

def load():
    S(s)
    n = input("\nВведите имя файла (желательно прописать полный путь до него, л\
ибо положите файл там же, где и программа): ")
    with open(n, "r") as f:
        a = f.read()
        a = a.lower()
        a = a.split()
        a = "... ".join(a) + '...'
        print('\n\n'  + a)
    
    input("\n\n\nЧтобы продолжить, нажмите ENTER...")


def key():
    S(s)
    n = input("\nВведите предложение с клавиатуры: ")
    n = n.lower()
    n = n.split()
    n = "... ".join(n) + '...'
    print('\n\n'  + n)

    input("\n\n\nЧтобы продолжить, нажмите ENTER...")


# ---------------------------[Главный исполняемый блок]------------------------

while(True):
    c = input(\
" * LOAD -- Ввести и преобразовать текст из файла\n\
 * KEY -- Ввести и преобразовать текст, введённый с клавиатуры\n\
 * END -- Завершить программу\n")
    c = c.lower()
    
    if c == 'load':
        load()
    elif c == 'key':
        key()
    elif c == 'end':
        break
    else:
        print("Упс, вы случайно ввели что-то не то...")
        S('sleep 1s')
    S(s)
