#! /usr/bin/python3

# ---------------------------[титульный экран]---------------------------------
from os import system as S
S("clear")

import startscreen
startscreen.load("DRAMATIC v0.2", "Делает текст драматичным за счёт многоточий\
\n\tИдеальный способ бесить собеседника", 5)

# ---------------------------[Блок функций]------------------------------------

# сам алгоритм преобразования
def conv(a):
    a, b = a.lower(), ""
    for i, item in enumerate(a):
        if item.isalnum() or (item in "\n\t "):
            b += item
    b = b.split()
    b = "... ".join(b) + "..."
    return b

# transfrom text from file
def load():
    n = input("\nВведите имя файла (желательно прописать полный путь до него,\
 либо положите файл там же, где и программа): ")
    with open(n, "r") as f:
        a = f.read()
        a = conv(a)
        print('\n\n'  + a)

# transform text from kryboard
def key():
    S("clear")
    n = input("\nВведите предложение с клавиатуры: ")
    n = conv(n)
    print('\n\n'  + n)


# ---------------------------[Главный исполняемый блок]------------------------

while(True):
    c = input("\
 * LOAD -- Ввести и преобразовать текст из файла\n\
 * KEY -- Ввести и преобразовать текст, введённый с клавиатуры\n\
 * END -- Завершить программу\n")
    S("clear")
    c = c.lower()
    
    if c == 'load':
        load()
    elif c == 'key':
        key()
    elif c == 'end':
        break
    else:
        print("Упс, вы случайно ввели что-то не то...")
        S('sleep 1s')
    input("\n\n\nНажмите ENTER, чтобы продолжить...")
    S("clear")

S("rm -rf __pycache__")
