#! /usr/bin/python3
from os import system as S
S("clear")

# ---------------------------[Титульный экран]---------------------------------
import startscreen
startscreen.load("ДУРКА v0.2", "Делает текст нечитабельным", 2)
S("rm -rf __pycache__")

# ---------------------------[Блок функций]------------------------------------

#### --------------[Алгоритмы редактирования]----------------------------------

# ПрЫгАюЩиЙ ТеКсТ
def jump(txt):
    tnt, flg = '', True
    for i, item in enumerate(txt):
        if flg:
            tnt += item.upper()
            flg = False
            continue
        else:
            tnt += item.lower()
            flg = True
    return tnt

# Убирает знаки препинания
def remove_punctuation_signs(txt):
    tnt = ''
    for i, item in enumerate(txt):
        if item.isalnum() or item.isspace():
            tnt += item
    return tnt

# Между слов ставит многоточия
def Dramatic(a):
    a, b = a.lower(), ""
    for i, item in enumerate(a):
        if item.isalnum() or (item in "\n\t "):
            b += item
    b = b.split()
    b = "... ".join(b) + "..."
    return b

# Делает текст капсом и разделяет пробелами буквы
def epic(txt):
    txt = txt.upper()
    txt = txt.split()
    tnt = ['']

    for i, item in enumerate(txt):
        for j, item in enumerate(txt[i]):
            tnt[i] += item + ' '
        tnt[i] += ' '
        tnt.append('')

    return ''.join(tnt)

#### --------------[Ввод/сохранение/загрузка текста]---------------------------
# Главная функция
def main(txt):
    choose = input("""Введите алгоритм редактирования:
	* 0 -- Делает буквы прописными через одну
	* 1 -- Убирает знаки препинания
	* 2 -- Между слов ставит многоточия
	* 3 -- Делает текст капсом и разделяет пробелами буквы
: """)

    if choose == '0':
        txt = jump(txt)
    elif choose == '1':
        txt = remove_punctuation_signs(txt)
    elif choose == '2':
        txt = Dramatic(txt)
    elif choose == '3':
        txt = epic(txt)
   
    # Сохранить в файл?
    ch = input("Сохранить в файл?[Y/N]: ")

    if ch == 'Y':
        name = input("Введите имя файла: ")
        save(txt, name)

    print(txt)
    input("...")
    S("clear")

# функция сохранения файла
def save(txt, tnt):
    # txt - сам текст
    # tnt - имя файла
	if '.txt' not in tnt:
		tnt += '.txt'
	with open(tnt, 'w') as F:
		F.write(txt)


# редактирование из файла
def FILE():
    S("ls --color=auto *.txt")
    name = input("Введите имя файла: ")
    if ".txt" not in name:
        name += ".txt"
    txt = ''
    with open(name, 'r') as F:
        txt = F.read()
    
    main(txt)

# редактирование из клавиатуры
def KEYBOARD():
    stroka = input("Введите строку: ")
    main(stroka)

# ---------------------------[Основной блок программы]-------------------------
while True:
    print("""
 * 0 -- Редактирование из файла
 * 1 -- Редактирование с клавиатуры
 * 2 -- Выход
    """)
    choose = input(": ")

    if choose == '0': FILE()
    elif choose == '1': KEYBOARD()
    elif choose == '2': break
input("Нажмите ENTER, чтобы завершить программу")
