#! /usr/bin/python3

# ---------------------------[Главный исполняемый блок]------------------------

stroka, word = input("Введите строку: "), ''

# ----- избавляемся от лишних символов
for item in stroka:
    if item.isalpha():
        word += item.upper()
# -----

# ----- считаем, сколько данная буква встречается в последовательности
world, i, k = list(), 0, True

for item in word:
    # Избавляемся от лишних повторений подсчёта букв
    for d in range(len(world)):
        if world[d][0] == item:
            k = False
            break
        else: k = True
    if not k:
        continue

    # Считаем
    world.append([item, 0])
    for j in word:
        if world[i][0] == j:
            world[i][1] += 1
    i+= 1
# -----

# ----- Сортируем двумерный массив: сначала в алфавитном порядке, потом в 
# ----- порядке убывания частоты повторения

world = sorted(world)

for d in range(len(world)):
    for i in range(1, len(world)):
        if world[i-1][1] > world[i][1]:
            world[i-1], world[i] = world[i], world[i-1]

# выводим строку
for d in range(len(world)):
    print(world[d][0], end='')
# -----
