#! /usr/bin/python3

N, flg = int(input("Введите количество чисел для последующей последовательностей(больше 6): ")), True
if N < 7:
    print(0)
    flg = False


numbers = list()
for i in range(N):
    if not flg:
        break
    numbers.append(int(input("Введите число: ")))

minimum = 1000000 
for i in range(N-7):
    if not flg:
        break
    for j in range(i+6, N):
        x = numbers[i]*numbers[j]
        if x % 2 == 0 and minimum > x:
            minimum = x
if flg:
    print(minimum)
